### ISSUE TITLE
Page classement: tri par score par nombre de pronostics par défaut

### ISSUE THREAD

**Issue by nicolionheart** [michelcourtade/Pronostics#16]
Actuellement plusieurs visites consécutives sur la page de classement peuvent donner des ordres différents pour des personnes ayant un score identique.
Idées de solutions:
- Mettre en place un tri par score DESC ET par par nombre de pronostics ASC (et éventuellement par pseudo ASC) par défaut -> un utilisateur ayant une meilleure moyenne sur ses pronostics est à priori "meilleur" que l'autre ayant le même score mais sur un nombre de pronos plus grand
- Implémenter la terminologie "Ex-aequo" pour même score/même nombre de pronos

**Comment by michelcourtade** [comment]
yes déjà remonté mais très pertinent ;)

**Comment by michelcourtade** [comment]
Allez, c'est en place ! 
On peut démarrer une nouvelle compet, comme ca tout le monde commence a 0 ! Je t'envoie une invit ;)
