### ISSUE TITLE
Liens vers les statistiques d'un joueur

### ISSUE THREAD

**Issue by nicolionheart** [michelcourtade/Pronostics#17]
Rendre plus facile l'accès aux statistiques d'un joueur: actuellement il est assez difficile de trouver le lien vers les statistiques d'un joueur, pourquoi ne pas rendre les pseudos cliquables dans la page Classement afin de pointer vers les statistiques et pronostics du joueur.

**Comment by michelcourtade** [comment]
oui tout a fait, avoir une page "User" qui reprend les stats du joueur par compet et au general

**Comment by michelcourtade** [comment]
Et oui 3 ans plus tard, cette page voit enfin le jour ! Comme quoi tout vient à point à qui ...
Merci @nicolionheart pour cette issue ! :D
Ca farte ?

**Comment by nicolionheart** [comment]
Oui ça va, je te remercie.
Content de voir que cette appli tourne toujours ! Un peu moins de constater
que tu ne m'as pas invité pour cet euro :'(

Et toi ça roule ?




Le jeu. 17 juin 2021 à 13:25, Michel Courtade ***@***.***> a
écrit :
